In [1]:
import numpy as np

a = np.array([[2,3],[5,2]])
print(a)

[[2 3]
 [5 2]]


In [6]:
d = np.array([[1,2,3,4,5],[2,4,6,8,10],[5,6,7,8,9]])

print(d)

print(d[1][2])
print(d[1,2])
print(d[1:,3:], type(d[1:,3:]))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 5  6  7  8  9]]
6
6
[[ 8 10]
 [ 8  9]] <class 'numpy.ndarray'>


In [8]:
d = np.array([1,2,3,4,5])
print(d.shape)

d = np.array([[1,2,3,4,5],[2,4,6,8,10]])
print(d.shape)

(5,)
(2, 5)


In [9]:
print(d.dtype)

int32


In [10]:
data = np.arange(1,5)
data.dtype

dtype('int32')

In [11]:
data.astype('float64')

array([1., 2., 3., 4.])

In [12]:
data.astype('int32')

array([1, 2, 3, 4])

In [13]:
# 0으로 이뤄진 배열 만들기
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
# 1로 이뤄진 배열 만들기
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
# 연속형 정수 생성하기
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 행과 열을 바꾸기
a = np.ones((2,4))
print(a)
b = np.transpose(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [1]:
import numpy as np

d = np.array([[1,2,3,4,5],[2,4,5,6,7],[6,5,7,8,9]])
d_list = [[1,2,3,4,5],[2,4,5,6,7],[6,5,7,8,9]]

# d_list [:2] = 0 오류 발생
d[:2] = 0
print(d)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [6 5 7 8 9]]


In [2]:
# 0~9까지 원소를 가지는 배열 arr 생성

arr = np.arange(10)
print(arr)

print(arr[:5])
print(arr[-3:])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[7 8 9]


In [3]:
arr1 = np.array([[2,3,4],[6,7,8]])

print(arr1[1,2])
print(arr1[:,2])

8
[4 8]


In [8]:
import usecsv, numpy as np

quest = np.array(usecsv.switch(usecsv.opencsv("quest.csv")))
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 6. 2. 5.]
 [3. 6. 4. 2. 5.]
 [3. 5. 4. 1. 6.]
 [3. 5. 5. 1. 3.]]


In [9]:
print(quest > 5)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False  True False False]
 [False  True False False False]
 [False False False False  True]
 [False False False False False]]


In [10]:
print(quest[quest > 5])

[6. 6. 6.]


In [11]:
quest[quest > 5] = 5
print(quest)

[[1. 2. 1. 2. 2.]
 [1. 3. 2. 3. 2.]
 [1. 4. 3. 3. 3.]
 [2. 5. 4. 4. 4.]
 [2. 5. 5. 2. 5.]
 [3. 5. 4. 2. 5.]
 [3. 5. 4. 1. 5.]
 [3. 5. 5. 1. 3.]]
